name: base
channels:
  - defaults
dependencies:
  - archspec=0.2.5
  - attrs=25.4.0
  - beautifulsoup4=4.14.2
  - boltons=25.0.0
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - certifi=2026.01.04
  - cffi=2.0.0
  - chardet=5.2.0
  - charset-normalizer=3.4.4
  - click=8.2.1
  - colorama=0.4.6
  - conda=26.1.0
  - conda-build=26.1.0
  - conda-index=0.7.0
  - conda-libmamba-solver=25.11.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - cpp-expected=1.1.0
  - distro=1.9.0
  - evalidate=2.0.3
  - expat=2.7.3
  - fmt=11.2.0
  - frozendict=2.4.6
  - idna=3.11
  - jinja2=3.1.6
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - libarchive=3.8.2
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcurl=8.18.0
  - libexpat=2.7.3
  - libffi=3.4.4
  - libiconv=1.16
  - libkrb5=1.22.1
  - liblief=0.12.3
  - libmamba=2.3.2
  - libmambapy=2.3.2
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - m2-msys2-runtime=2.5.0.17080.65c939c
  - m2-patch=2.7.5
  - menuinst=2.4.2
  - msgpack-python=1.1.1
  - msys2-conda-epoch=20160418
  - nlohmann_json=3.11.2
  - openssl=3.0.19
  - packaging=25.0
  - pcre2=10.46
  - pip=25.3
  - pkginfo=1.12.1.2
  - platformdirs=4.5.0
  - pluggy=1.5.0
  - py-lief=0.12.3
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.12.0
  - python-libarchive-c=5.3
  - pytz=2025.2
  - pyyaml=6.0.3
  - referencing=0.37.0
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.5
  - rpds-py=0.28.0
  - ruamel.yaml=0.18.16
  - ruamel.yaml.clib=0.2.14
  - setuptools=80.10.1
  - simdjson=3.10.1
  - soupsieve=2.5
  - sqlite=3.51.1
  - tk=8.6.15
  - tqdm=4.67.1
  - truststore=0.10.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - ucrt=10.0.22621.0
  - urllib3=2.6.3
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.46.3
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zlib=1.3.1
  - zstandard=0.24.0
  - zstd=1.5.7
  - pip:
      - --index-url https://download.pytorch.org/whl/xpu
      - absl-py==2.4.0
      - ale-py==0.11.2
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - cycler==0.12.1
      - dpcpp-cpp-rt==2025.3.1
      - farama-notifications==0.0.4
      - filelock==3.20.0
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - grpcio==1.78.0
      - gymnasium==1.2.3
      - imagehash==4.3.2
      - intel-cmplr-lib-rt==2025.3.1
      - intel-cmplr-lib-ur==2025.3.1
      - intel-cmplr-lic-rt==2025.3.1
      - intel-opencl-rt==2025.3.1
      - intel-openmp==2025.3.1
      - intel-pti==0.15.0
      - intel-sycl-rt==2025.3.1
      - kiwisolver==1.4.9
      - markdown==3.10.1
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mkl==2025.3.0
      - mpmath==1.3.0
      - networkx==3.6.1
      - numpy==2.4.2
      - onemkl-license==2025.3.0
      - onemkl-sycl-blas==2025.3.0
      - onemkl-sycl-dft==2025.3.0
      - onemkl-sycl-lapack==2025.3.0
      - onemkl-sycl-rng==2025.3.0
      - onemkl-sycl-sparse==2025.3.0
      - opencv-python==4.13.0.90
      - pandas==3.0.0
      - pillow==12.0.0
      - polars==1.37.1
      - polars-runtime-32==1.37.1
      - protobuf==6.33.5
      - psutil==7.2.2
      - pyelftools==0.32
      - pygame==2.6.1
      - pygments==2.19.2
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pywavelets==1.9.0
      - rich==14.3.2
      - scipy==1.17.0
      - six==1.17.0
      - stable-baselines3==2.7.1
      - sympy==1.14.0
      - tbb==2022.3.0
      - tcmlib==1.4.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - torch==2.10.0+xpu
      - torchaudio==2.10.0+xpu
      - torchvision==0.25.0+xpu
      - triton-xpu==3.6.0
      - tzdata==2025.3
      - ultralytics==8.4.9
      - ultralytics-thop==2.0.18
      - umf==1.0.2
      - werkzeug==3.1.5
prefix: C:\Users\human\miniconda3\envs\yolo
